properties:
  enabled: false
  remote-address: 127.0.0.1
  security:
    username: xinzhe
    password: 123456
    roles: [user, admin]

acme:
  enabled: false
  remote-address: 127.0.0.1
  security:
    username: xinzhe
    password: 123456
    roles: [user, admin, customer]

server:
  port: 8092

testprop:
  enabled: true
  remote-address: 127.1.1.1
  security:
    username: test
    password: pass

#database configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456

#mybatis configuration
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xinzhe.bean
